name: img-receipt ci

on:
  #  push:
  #    branches: [ develop ]
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: get git hash
        id: get_hash
        run: echo ::set-output name=HASH::$(echo $GITHUB_SHA | cut -c1-8)

      - name: get build time
        id: get_time
        run: echo ::set-output name=TIMESTAMP::$(date '+%Y-%m-%d_%H:%M:%S_%Z')

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: docker build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: ${{ github.event_name == 'push' }}
          tags: |
            suapapa/img-receipt:latest
            suapapa/img-receipt:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            BUILD_TAG=${{ steps.get_version.outputs.VERSION }}
            BUILD_TIME=${{ steps.get_time.output.TIMESTAMP }}
            GITHASH=${{ steps.get_hash.outputs.HASH }}
